# Generated by Django 4.2.3 on 2023-12-04 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humans', '0004_doctor_date_added_doctor_date_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='last_appointment',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='next_appointment',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
