# Generated by Django 4.2.3 on 2023-12-04 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_alter_appointment_doctor_alter_appointment_patient'),
        ('humans', '0005_patient_last_appointment_patient_next_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='specialties',
            field=models.ManyToManyField(related_name='doctor_specialties', to='management.doctorspecialty'),
        ),
    ]
