# Generated by Django 4.2.3 on 2024-02-27 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('humans', '0006_alter_doctor_specialties'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['next_appointment']},
        ),
    ]
