# Generated by Django 4.2.3 on 2023-12-04 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('humans', '0005_patient_last_appointment_patient_next_appointment'),
        ('management', '0002_testresult_date_added_testresult_date_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='humans.doctor'),
        ),
    ]
