# Generated by Django 4.2.3 on 2023-12-04 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_alter_appointment_doctor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['appointment_date']},
        ),
    ]
