# Generated by Django 4.2.3 on 2024-02-27 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('humans', '0007_alter_patient_options'),
        ('management', '0005_alter_appointment_doctor_alter_appointment_patient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalhistory',
            old_name='prescription',
            new_name='medication_name',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='medical_history',
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='instructions',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='symtoms',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='testresult',
            name='lab_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='testresult',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='humans.patient'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='test_approved_by',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='testresult',
            name='tested_by',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_records', to='humans.doctor'),
        ),
        migrations.DeleteModel(
            name='Prescription',
        ),
    ]
